services:
  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  node_exporter:
    image: "quay.io/prometheus/node-exporter:latest"
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    #network_mode: host
    ports:
      - "9100:9100"
    restart: unless-stopped
    pid: host
    volumes:
      - '/:/host:ro,rslave'

  petshop:
    image: "harbor.sflabs.com.br/processo/petshop:latest"
    container_name: petshop
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  prometheus-data:
