- name: Install dependencies
  hosts: hosts
  become: yes
  tasks:
    - name: Install git
      package:
        name: git
        state: present
    - name: Install docker
      package:
        name: docker
        state: present
    - name: Install docker-compose
      package:
        name: docker-compose
        state: present

- name: Clone Repo
  hosts: hosts
  become: yes
  tasks:
    - name: Clone
      ansible.builtin.git:
        repo: https://github.com/silmarp/visio-petshop-monitoring.git
        dest: /deploy
        # can't run task without force because grafana constantly modifies files from volume folder
        force: true

- name: Run compose
  hosts: hosts
  become: yes
  tasks:
    - name: Tear down existing services
      community.docker.docker_compose:
        project_src: /deploy 
        state: absent

    - name: Create and start services
      community.docker.docker_compose:
        project_src: /deploy
      register: output

